spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: demo

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true